CREATE DATABASE IF NOT EXISTS techblog2
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_unicode_ci;
USE techblog2;

CREATE TABLE techblog2.Base_Resource
	(
	  Id          BIGINT UNSIGNED NOT NULL
	, IsDeleted   TINYINT NOT NULL DEFAULT 0
	, Name        VARCHAR (150) NOT NULL
	, Size        BIGINT UNSIGNED NOT NULL
	, Path        VARCHAR (500) NOT NULL
	, ContentType VARCHAR (100) NOT NULL
	, MD5         VARCHAR (50) NOT NULL
	, Uploader_Id BIGINT UNSIGNED NOT NULL
	, UploadTime  DATETIME NOT NULL
	, PRIMARY KEY (Id)
	) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4;

CREATE TABLE techblog2.Base_Role
	(
	  Id        BIGINT UNSIGNED NOT NULL
	, IsDeleted TINYINT NOT NULL DEFAULT 0
	, Encode    VARCHAR (20) NOT NULL
	, Name      VARCHAR (20) NOT NULL
	, IsDefault TINYINT NOT NULL DEFAULT 0
	, PRIMARY KEY (Id)
	) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4;

CREATE TABLE techblog2.Base_UserRole
	(
	  User_Id BIGINT UNSIGNED NOT NULL
	, Role_Id BIGINT UNSIGNED NOT NULL
	, PRIMARY KEY (User_Id, Role_Id)
	) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4;

CREATE TABLE techblog2.Blog_Articles
	(
	  Id          BIGINT UNSIGNED NOT NULL
	, IsDeleted   TINYINT NOT NULL DEFAULT 0
	, Title       VARCHAR (100) NOT NULL
	, Content     MEDIUMTEXT NOT NULL
	, Category_Id BIGINT UNSIGNED NOT NULL
	, ViewsCount  INT NOT NULL
	, CreateTime  DATETIME NOT NULL
	, ModifyTime  DATETIME
	, PRIMARY KEY (Id)
	, KEY IX_Blog_Articles_Category_Id (Category_Id)
	) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4;

CREATE TABLE techblog2.Blog_ArticleTags
	(
	  Article_Id BIGINT UNSIGNED NOT NULL
	, Tag_Id     BIGINT UNSIGNED NOT NULL
	, PRIMARY KEY (Article_Id, Tag_Id)
	, KEY IX_Blog_ArticleTags_Tag_Id (Tag_Id)
	) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4;

CREATE TABLE techblog2.Blog_Categories
	(
	  Id         BIGINT UNSIGNED NOT NULL
	, IsDeleted  TINYINT NOT NULL DEFAULT 0
	, Name       VARCHAR (20) NOT NULL
	, CreateTime DATETIME NOT NULL
	, PRIMARY KEY (Id)
	, KEY IX_Blog_Categories_Name (Name)
	) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4;

CREATE TABLE techblog2.Blog_Comments
	(
	  Id          BIGINT UNSIGNED NOT NULL
	, IsDeleted   TINYINT NOT NULL DEFAULT 0
	, User_Id     BIGINT NOT NULL
	, ReplyTo     VARCHAR(20) NULL
	, Article_Id  BIGINT UNSIGNED NOT NULL
	, Parent_Id   BIGINT UNSIGNED
	, Content     VARCHAR (1000) NOT NULL
	, CommentTime DATETIME NOT NULL
	, ModifyTime  DATETIME
	, PRIMARY KEY (Id)
	, KEY IX_Blog_Comments_Article_Id (Article_Id)
	, KEY IX_Blog_Comments_User_Id (User_Id)
	, KEY IX_Blog_Comments_Parent_Id (Parent_Id)
	) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4;

CREATE TABLE techblog2.Blog_Tags
	(
	  Id        BIGINT UNSIGNED NOT NULL
	, IsDeleted TINYINT NOT NULL DEFAULT 0
	, TKey      VARCHAR (20) NOT NULL
	, Name      VARCHAR (20) NOT NULL
	, PRIMARY KEY (Id)
	, KEY IX_Blog_Tags_TKey (TKey)
	) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4;

CREATE TABLE techblog2.Base_User
    (
      Id         BIGINT UNSIGNED NOT NULL
	, IsDeleted  TINYINT(1) NOT NULL DEFAULT 0
    , Account    VARCHAR(15) NOT NULL
    , Name       VARCHAR(20) NOT NULL
    , Hash       VARCHAR(64) NOT NULL
    , Salt       VARCHAR(64) NOT NULL
    , Email      VARCHAR(50) NOT NULL
    , Avatar_Id  BIGINT UNSIGNED NOT NULL
	, IsDisabled TINYINT(1) NOT NULL DEFAULT 0
	, IsAdmin    TINYINT(1) NOT NULL DEFAULT 0
	, PRIMARY KEY (Id)
    ) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4;

INSERT INTO techblog2.Base_Role(Id,IsDeleted,Encode,Name,IsDefault)
VALUES(1202280255822135296,0,'CommonUser','用户',1);

INSERT INTO techblog2.Base_User(Id,IsDeleted,Account,Name,Hash,Salt,Email,Avatar_Id,IsDisabled,IsAdmin)
VALUES(1202286957502038016,0,'admin','admin','B708239C2AE0B760658E1ED11DEF8CCA27B61984F75AEE1E46D032DFC6F61F98','CE64836842FA669ADD6003C8D60B2284E4A9F89FA4100B3609F46E3CB95D8075','test1@163.com',0,0,1);

INSERT INTO techblog2.Base_UserRole(User_Id,Role_Id) VALUES(1202286957502038016,1202280255822135296);