services:
  techblogcore.aot:
    image: ${DOCKER_REGISTRY-}techblogcoreaot
    build:
      context: TechBlogCore.AOT
      dockerfile: Dockerfile
    ports:
      - "7085:8080"

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testpswd
      MYSQL_DATABASE: techblog2
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: testblogpswd
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
  techblogcore.vue:
    image: ${DOCKER_REGISTRY-}techblogcorevue
    build:
      context: ../TechBlogCore.Vue
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    depends_on:
      - techblogcore.aot
volumes:
  mysql_data: